# Generated by Django 5.2.6 on 2025-10-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameEngine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venture",
            name="success_rate",
        ),
        migrations.AlterField(
            model_name="playerbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_badges",
                to="gameEngine.badge",
            ),
        ),
        migrations.AlterField(
            model_name="playerbadge",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_badges",
                to="gameEngine.playerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="stars",
            field=models.IntegerField(default=100),
        ),
    ]
