# Generated by Django 5.2.6 on 2025-06-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameEngine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="stars",
            field=models.IntegerField(default=0),
        ),
    ]
