# Generated by Django 5.2.6 on 2025-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameEngine", "0002_alter_playerprofile_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="venture",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
