# Generated by Django 5.2.6 on 2025-11-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gameEngine", "0003_venture_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venture",
            name="token_id",
        ),
    ]
