# Generated by Django 5.2.6 on 2025-10-30 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tickets_purchased", models.IntegerField(default=1)),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("shares_earned", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("completed_game", models.BooleanField(default=False)),
                ("completion_time", models.IntegerField(blank=True, null=True)),
                (
                    "transaction_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "nft_token_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matrix_participations",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="MatrixSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_layer", models.IntegerField(default=0)),
                ("patterns_found", models.IntegerField(default=0)),
                ("moves_made", models.IntegerField(default=0)),
                ("time_elapsed", models.IntegerField(default=0)),
                ("matrix_data", models.JSONField(default=dict)),
                ("discovered_patterns", models.JSONField(default=list)),
                ("strategic_decisions", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_sessions",
                        to="matrix_ceo.playerparticipation",
                    ),
                ),
            ],
            options={
                "db_table": "matrix_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🚀", max_length=10)),
                ("total_shares", models.IntegerField(default=1000)),
                ("ceo_shares", models.IntegerField(default=200)),
                ("participant_shares", models.IntegerField(default=800)),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                ("matrix_complexity", models.IntegerField(default=5)),
                ("time_limit_hours", models.IntegerField(default=24)),
                ("required_patterns", models.IntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Accepting Participants"),
                            ("running", "Running - Game Active"),
                            ("completed", "Completed - CEO Selected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "rwa_contract_address",
                    models.CharField(blank=True, max_length=42, null=True),
                ),
                (
                    "nft_ticket_contract",
                    models.CharField(blank=True, max_length=42, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceo_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_projects",
                        to="matrix_ceo.playerparticipation",
                    ),
                ),
            ],
            options={
                "db_table": "matrix_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="playerparticipation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="matrix_ceo.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playerparticipation",
            unique_together={("player", "project")},
        ),
    ]
