# Generated by Django 5.2.6 on 2025-10-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_ceo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceoselection",
            name="application_nft_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="ceoselection",
            name="ft_token_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ceoselection",
            name="nft_serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
