# Generated by Django 5.2.6 on 2025-10-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_ceo", "0002_ceoselection_application_nft_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ceoselection",
            old_name="ft_token_id",
            new_name="nft_token_id",
        ),
    ]
