# Generated by Django 5.2.6 on 2025-10-31 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_ceo", "0003_rename_ft_token_id_ceoselection_nft_token_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Ticket"),
                            ("premium", "Premium Ticket"),
                            ("vip", "VIP Ticket"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("price_hbar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("token_id", models.CharField(blank=True, max_length=100, null=True)),
                ("nft_serial", models.BigIntegerField(blank=True, null=True)),
                (
                    "user_account_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceo_selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_purchases",
                        to="matrix_ceo.ceoselection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "ceo_selection", "status")},
            },
        ),
    ]
