# Generated by Django 5.2.6 on 2025-10-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web3", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproposal",
            name="hcs_topic_id",
            field=models.CharField(
                blank=True,
                help_text="HCS Topic ID for this proposal",
                max_length=100,
                null=True,
            ),
        ),
    ]
